djsport/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2017 Marco Marinello <marco.marinello@fuss.bz.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.main, name='main-index'),
    url(r'^landing$', views.landing, name='landing'),
    url(r'^login/$', views.logon, name='login'),
    url(r'^login/logout$', views.logoff, name='logout'),
    url(r'^passwd$', views.password_change, name="password_change"),
    url(r'^sportday/', include(('sportday.urls', 'sportday'), namespace='sportday')),
]

sportday/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2017 Marco Marinello <marco.marinello@fuss.bz.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^class/(?P<id>[0-9]+)$', views.class_show, name='class'),
    url(r'^class/(?P<id>[0-9]+)/ajax$', views.class_show_ajax, name='class-ajax'),
    url(r'^class/(?P<id>[0-9]+)/get_student$',
        views.student_get,
        name='get-student'
    ),
    url(r'^class/(?P<id>[0-9]+)/save_student$',
        views.student_post,
        name='save-student'
    ),
    url(r'^class/(?P<id>[0-9]+)/report$',
        views.class_report,
        name='class-report'
    ),
    url(r'^class/(?P<id>[0-9]+)/add_spokeperson', views.add_spokeperson, name='add_spokeperson'),
    url(r'^class/choice$', views.class_choice, name='class-choice'),
    url(r'^competition/choice$',
        views.competition_choice,
        name='competition-choice'
    ),
    url(r'^competition/(?P<id>[0-9]+)$',
        views.competition,
        name='competition'
    ),
    url(r'^competition/(?P<id>[0-9]+)/report$',
        views.competition_report,
        name='competition-report'
    ),
    url(r'^competition/(?P<id>[0-9]+)/ajax$',
        views.competition_ajax,
        name='competition-ajax'
    ),
    url(r'^competition/(?P<id>[0-9]+)/act$',
        views.part_act,
        name='partecipation-action'
    ),
    url(r'^ranking/choice$', views.ranking_choice, name='ranking-choice'),
    url(r'^ranking/print.pdf$', views.ranking, name='competition-ranking'),
]

sportday/views.py
# -*- coding: utf-8 -*-
# Copyright (c) 2017 Marco Marinello <marco.marinello@fuss.bz.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q
from datetime import timedelta
from .models import Account, Class, Student, Competition, Partecipation
from .decorators import has_sportday_account, admins_this_class, \
     teacher_or_result
import json
from . import report


# Some danger message
def add_danger(request, message):
    messages.add_message(request, "50", message, extra_tags="danger")
messages.danger = add_danger


@login_required
@has_sportday_account
def index(request, account):
    if account.is_teacher or account.inputs_results:
        return render(request, "sportday/landing.html", {"account": account})
    if len(account.classes.all()) > 1:
        return redirect("sportday:class-choice")
    return redirect("sportday:class", id=account.classes.all()[0].id)


@login_required
@has_sportday_account
def class_choice(request, account):
    return render(
        request,
        "sportday/class-choice.html",
        {"account": account}
    )


@login_required
@has_sportday_account
@admins_this_class
def class_show(request, id=None, account=None):
    cl = get_object_or_404(Class, id=id)
    students = Student.objects.filter(schoolclass=cl)
    competitions = Competition.objects.filter(
        available_in_schools__in=[cl.school]
    )
    return render(
        request,
        "sportday/class.html",
        {"class": cl, "students": students, "competitions": competitions, "show_private": account.is_teacher}
    )


def select_icon(student):
    if len(Partecipation.objects.filter(student=student)) > 0:
        return "<i class='fa fa-check fa-2x green'></i>"
    return "<i class='fa fa-times fa-2x red'></i>"


def call_show_student_btn(student):
    return ('<i class="fa fa-pencil fa-2x" '+
    'onclick="loadStudent(\'%s\');" title="'+
    '%s %s" data-toggle="modal" data-target="#studentbox"></i>') % (
        student.id, _('Visualizza la scheda di'), student.get_full_name())


@login_required
@has_sportday_account
@admins_this_class
def class_show_ajax(request, id, account):
    # Fetch vars from request
    start = int(request.GET.get("iDisplayStart", "0"))
    length = int(request.GET.get("iDisplayLength", "30"))
    query = request.GET.get("sSearch", False)

    # Compute data
    db = Student.objects.filter(schoolclass_id=id)
    all_length = len(db)
    if query:
        db = db.filter(Q(last_name__icontains=query)|
                       Q(first_name__icontains=query))
    full_length = len(db)

    students = [[
        select_icon(student),
        ("%s %s" % (student.last_name, student.first_name)).strip(),
        account.is_teacher and student.date_of_birth.strftime("%d/%m/%Y") or "",
        call_show_student_btn(student)
        ] for student in db[start:start+length]]

    return HttpResponse(
        json.dumps(
            {"aaData": students,
             "iTotalDisplayRecords": len(db),
             "iTotalRecords": all_length,
             "sEcho": None
             }
            )
        )


@login_required
@has_sportday_account
@admins_this_class
def add_spokeperson(request, id, account):
    if not account.is_teacher:
        messages.danger(request, _("Solo i docenti possono aggiungere nuovi rappresentanti!"))
        return redirect("sportday:class", id=id)
    data = [request.POST.get(x) for x in ("last_name", "first_name", "email")]
    if None in data:
        messages.danger(request, _("Prego compilare tutti i campi!"))
        return redirect("sportday:class", id=id)
    try:
        this_class = Class.objects.get(id=id)
        username = "%s%s" %( data[0], data[1][:3] )
        username = "%s.%s" % (this_class.school.code, username.lower())
        u = User.objects.create(
            username=username,
            last_name=data[0].title(),
            first_name=data[1].title(),
            email=data[2]
        )
        password = User.objects.make_random_password()
        u.set_password(password)
        u.save()
        cl = Account.objects.create(
            user=u
        )
        cl.classes.add(this_class)
        cl.save()
        messages.success(request, _("Rappresentante aggiunto con successo."))
        return render(request, "sportday/newspokeperson.html", {"newuser": cl, "pw": password})
    except Exception as E:
        messages.danger(request, "%s" % E)
    return redirect("sportday:class", id=id)


def render_partecipation_list(student):
    return [a.competition.id for a in Partecipation.objects.filter(
        student=student)]


@login_required
@has_sportday_account
@admins_this_class
def student_get(request, id, account):
    student = request.POST.get("student", False)
    if not student:
        return HttpResponse(json.dumps({
            "status": "error", "error": "Missing student id"
        }))
    try:
        st = Student.objects.get(id=student, schoolclass__id=id)
        return HttpResponse(
            json.dumps(
                {"last_name": st.last_name,
                 "first_name": st.first_name,
                 "full_name": st.get_full_name(),
                 "date_of_birth": account.is_teacher and st.date_of_birth.strftime("%d/%m/%Y") or str(_("nascosta")),
                 "competitions": render_partecipation_list(st),
                 "status": "success"
                }
            )
        )
    except Exception as e:
        return HttpResponse(json.dumps({
            "status": "error", "error": str(e)
        }))


@login_required
@has_sportday_account
@admins_this_class
def student_post(request, id, account):
    student = request.POST.get("student", False)
    if not student:
        return HttpResponse(json.dumps({
            "status": "error", "error": "Missing student id"
        }))
    try:
        student = Student.objects.get(id=request.POST["student"], schoolclass__id=id)
        # Cleanup all partecipations
        Partecipation.objects.filter(student=student).delete()
        # Recreate requested partecipations
        for i in json.loads(request.POST["competitions"]):
            Partecipation.objects.create(student=student, competition_id=int(i))
        return HttpResponse(json.dumps({
            "status": "success"
        }))
    except Exception as e:
        return HttpResponse(json.dumps({
            "status": "error", "error": str(e)
        }))


@login_required
@has_sportday_account
@admins_this_class
def class_report(request, id, account):
    cl = get_object_or_404(Class, id=id)
    return report.class_report(request, cl, account.is_teacher)


@login_required
@has_sportday_account
@teacher_or_result
def competition_choice(request, account):
    return render(
        request,
        "sportday/competitions.html",
        {"competitions": Competition.objects.all()}
    )


@login_required
@has_sportday_account
@teacher_or_result
def competition(request, account, id):
    c = get_object_or_404(Competition, id=id)
    cats_pre = settings.CATEGORIES.keys()
    colors = ["warning", "info", "dark", "secondary"]
    cats = []
    i = 0
    for a in cats_pre:
        try:
            cats.append([a, colors[i]])
        except:
            cats.append([a, colors[0]])
        i += 1
    return render(
        request,
        "sportday/competition.html",
        {"competition": c, "cats": cats}
    )


@login_required
@has_sportday_account
@teacher_or_result
def competition_report(request, account, id):
    if not request.POST:
        return HttpResponse("404: Not found", status=404)
    c = get_object_or_404(Competition, id=id)
    db = Partecipation.objects.filter(competition=c, student__schoolclass__school__in=account.determine_school())
    cat = ""
    if request.POST["cat"] != "all":
        cat = request.POST["cat"]
        years = settings.CATEGORIES[request.POST["cat"]]
        db = db.filter(student__date_of_birth__year__in=years)
    if request.POST["sex"] != "all":
        cat += request.POST["sex"]
        db = db.filter(student__sex=request.POST["sex"].upper())
    return report.competition_report(request, c, db, cat.upper())


def aprop_links(account, partecipation):
    name = partecipation.student.get_full_name().replace("'", "&#39;")
    link = ""
    if partecipation.time_result or partecipation.meters_result:
        link = "<a class='btn btn-lg "
        link += "btn-success fa fa-check"
        link += " fa-nx btn-table' title='%s' " % (
            _("Modifica partecipazione di %(name)s (risultato: %(r)s)") % {
                    "name": name,
                    "r": (partecipation.time_result or partecipation.meters_result)
                }
        )
        link += "onclick='loadInsDataModal(\"%s\", \"%s\", \"%s\");'></a>" % (
            partecipation.id, name,
            (partecipation.time_result or partecipation.meters_result)
        )
    else:
        link = "<a class='btn btn-lg "
        link += "btn-primary fa fa-pencil"
        link += " fa-nx btn-table' title='%s' " % (
            _("Modifica partecipazione di %s") % name
        )

sportday/templates/sportday/base.html
{% load i18n static %}
<html>
	<head>
		<title>{% block title %}Base template{% endblock %} - SportDay</title>

		<meta charset="utf-8">
		<meta name="author" content="Marco Marinello" >
		<meta name="copyright" content="Marco Marinello">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">
		<link rel="stylesheet" href="{% static 'css/base.css' %}">

		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

		{% block extrahead %}{% endblock %}
	</head>
	<body>
		<!-- info modal -->
		<div class="modal animated lightSpeedIn" id="infobox">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">SportDay - Organizzatore della giornata sportiva</h5>
					</div>
					<div class="modal-body">
						<p class="text-center">
							<small>{% trans "Eccetto ove diversamente indicato il software è da intendersi" %}</small><br>
							Copyright (&copy;) 2017 Marco Marinello
						</p>
						{% trans "Utilizza" %}:
						<ul>
							<li>Python</li>
							<li>The Django Framework</li>
							<li>Bootstrap</li>
							<li>FontAwesome</li>
							<li>jQuery</li>
							<li>PopperJs</li>
							<li>DataTables</li>
						</ul>
					</div>
					<div class="modal-footer">
						<a href="#" class="btn btn-lg btn-dange btn-primary btn-small" data-dismiss="modal">
							{% trans "Chiudi" %}
						</a>
					</div>
				</div>
			</div>
		</div>
		<!-- end info modal -->
		<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-red">
			<a class="navbar-brand" href="{% url 'main-index' %}">SportDay</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto" style="margin-left: 2%;">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'sportday:index' %}">
							<i class="fa fa-home" aria-hidden="true"></i> &nbsp; {% trans "Pagina iniziale" %}
						</a>
					</li>
					{% if account.classes.all|length > 1 %}
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'sportday:class-choice' %}">
							<i class="fa fa-users" aria-hidden="true"></i> &nbsp; {% trans "Classi" %}
						</a>
					</li>
					{% endif %}
					{% if account.is_teacher or account.inputs_results %}
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'sportday:competition-choice' %}">
							<i class="fa fa-star-o" aria-hidden="true"></i> &nbsp; {% trans "Gare" %}
						</a>
					</li>
					{% endif %}
				</ul>
				<ul class="navbar-nav navbar-right">
					<li class="nav-item active">
						<a class="nav-link">{{ user.get_full_name }} ({{ user.username }})</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link fa fa-info fa-nx" href="#" title="{% trans 'Informazioni' %}" data-toggle="modal" data-target="#infobox"></a>
						<a class="nav-link fa fa-key fa-nx" href="{% url 'password_change' %}" title="{% trans 'Cambio password' %}"></a>
						{% if user.is_staff %}
						<a class="nav-link fa fa-gear fa-nx" href="{% url 'admin:index' %}" title="{% trans 'Amministrazione' %}"></a>
						{% endif %}
						<a class="nav-link fa fa-power-off fa-nx" href="{% url 'logout' %}" title="{% trans 'Logout' %}"></a>
					</li>
				</ul>
			</div>
		</nav>
		{% block content %}
			<div class="container">
				{% block notify %}{% endblock %}
				{% for message in messages %}
				<div class="alert alert-{{message.tags}}" onclick="$(this).slideUp();">
					<strong>{{ message }}</strong><p class="close" onclick="$(this).parent().slideUp();" style="cursor: default;"><i class="fa fa-close"></i></p>
				</div>
				{% endfor %}
				<div class="jumbotron">
					{% block standardcontent %}
					{% endblock %}
				</div>
			</div>
		{% endblock %}
	</body>
</html>

sportday/templates/sportday/class.html
{% extends "sportday/base.html" %}{% load i18n static %}
{% block title %}{% trans "Classe" %} {{ class.name }}{% endblock %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
{% endblock %}
{% block notify %}<div class="alert alert-success text-center" id="success-alert" style="display: none;"></div>{% endblock %}
{% block standardcontent %}
<!-- spokeperson adding modal -->
<div class="modal" id="addspokeperson" data-backdrop="static" data-keyboard="false">
	<form action="{% url 'sportday:add_spokeperson' id=class.id %}" method="POST" id="spk-form">{% csrf_token %}
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title opensans">{% trans "Nuovo rappresentante di classe per la" %} {{ class.name }}, {{ class.school.name }}</h5>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-lg-2 opensans">{% trans "Cognome" %}:</div>
						<div class="col-lg-4"><input type="text" name="last_name" class="btn-block text-center" placeholder="{% trans 'Cognome' %}" required></div>
						<div class="col-lg-2 opensans text-center">{% trans "Nome" %}:</div>
						<div class="col-lg-4"><input type="text" name="first_name" class="btn-block text-center" placeholder="{% trans 'Nome' %}" required></div>
					</div>
					<div class="row">
						<div class="col-lg-2 opensans">{% trans "E-mail" %}:</div>
						<div class="col-lg-10"><input type="email" class="btn-block text-center" name="email" placeholder="{% trans 'Indirizzo e-mail' %}" required autofocus></div>
					</div>
				</div>
				<div class="modal-footer">
					<a class="btn btn-lg btn-danger fa fa-times" href="#" data-dismiss="modal">{% trans "Annulla" %}</a>
					<a class="btn btn-lg btn-success fa fa-check" href="#" onclick="$('#spk-form').submit();">{% trans "Salva" %}</a>
				</div>
			</div>
		</div>
	</form>
</div>
<!-- end spokeperson adding modal -->
<!-- student modal -->
<div class="modal" id="studentbox" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modal-title"></h5>
			</div>
			<div class="modal-body">
				<p id="modal-wait" class="text-center"><i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i></p>
				<div class="alert alert-danger text-center" id="modal-error-alert" style="display: none;"></div>
				<div class="alert alert-success text-center" id="modal-success-alert" style="display: none;"></div>
				<div id="modal-content" class="row">
					<div class="col-md-6">
						<strong>{% trans "Cognome" %}:</strong> <a id="student-last_name"></a>
					</div>
					<div class="col-md-6">
						<strong>{% trans "Nome" %}:</strong> <a id="student-first_name"></a>
					</div>
					<div class="col-md-6">
						<strong>{% trans "Data di nascita" %}:</strong> <a id="student-date_of_birth"></a>
					</div>
					<div class="col-md-12 padding-bottom">
						<strong>{% trans "Gare scelte" %}</strong>
					</div>
					{% for c in competitions %}
					<div class="col-md-6">
						<label class="btn btn-lg btn-default active" for="c-{{c.id}}"><input type="checkbox" class="competition" value="{{ c.id }}" id="c-{{c.id}}"> {{c}}</label>
					</div>
					{% endfor %}
					<input type="hidden" id="student-id">
				</div>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn btn-lg btn-primary btn-small" style="display: none;" id="modal-save-btn">
					{% trans "Salva" %} &nbsp; <i class="fa fa-floppy-o" aria-hidden="true"></i>
				</a>
				<a href="#" class="btn btn-lg btn-dange btn-danger btn-small" data-dismiss="modal" style="display: none;" id="modal-close-btn">
					{% trans "Chiudi" %} &nbsp; <i class="fa fa-close" aria-hidden="true"></i>
				</a>
				<a href="#" class="btn btn-lg btn-success btn-small" style="display: none;" id="modal-saveclose-btn">
					{% trans "Salva e chiudi" %} &nbsp; <i class="fa fa-check" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
</div>
<!-- end student modal -->

<div class="row">
	<div class="col-md-8">
		<p class="page-title">{% trans "Classe" %} {{ class.name }} - {{ class.school.code }}: {{ class.school.name }}</p>
	</div>
	<div class="col-md-4" style="text-align: right;">
		{% if account.is_teacher %}
		<a class="btn btn-lg btn-warning fa fa-user-plus fa-nx" title="{% trans 'Aggiunta rappresentante di classe' %}" href="#" data-toggle="modal" data-target="#addspokeperson"></a>
		{% endif %}
		<a class="btn btn-lg btn-primary fa fa-print fa-nx" title="{% trans 'Riassunto in PDF' %}" href="{% url 'sportday:class-report' id=class.id %}"></a>
	</div>
</div>
<br>
<table id="table" class="table table-bordered table-striped">
	<thead class="thead-green">
		<tr>
			<th></th>
			<th>{% trans "Cognome e Nome" %}</th>
			<th>{% if show_private %}{% trans "Data di nascita" %}{% endif %}</th>
			<th></th>
		</tr>
	</thead>
	<tbody></tbody>
</table>

<script type="text/javascript" >
	var dt = $("#table").DataTable({
		"bServerSide": true,
		"ajaxSource": "{% url 'sportday:class-ajax' id=class.id %}",
		"pageLength": 25,
		"language": {"url": "{% static 'locale' %}/{{LANGUAGE_CODE}}.json"},
		"columnDefs": [
			{"orderable": false, "targets": [0, 1, 2, 3]}
		]
	});


	function displayModalError(error) {
		$("#modal-wait").hide();
		$("#modal-content").hide();
		$("#modal-close-btn").show();
		$("#modal-error-alert").show().html(error);
	}

	function displayModalSuccess(success) {
		$("#modal-success-alert").show().html(success);
	}

	function displayInlineSuccess(success) {
		$("#success-alert").html(success).slideDown();
	}

	function loadStudent(st) {
		pos = $(window).scrollTop();
		// hide all before start
		$("#success-alert").slideUp();
		$("#modal-content").hide();
		$("#modal-error-alert").hide();
		$("#modal-success-alert").hide();
		$("#modal-close-btn").hide();
		$("#modal-saveclose-btn").hide();
		$("#modal-save-btn").hide();
		// show wait and change title
		$("#modal-wait").show();
		$("#modal-title").text("{% trans 'Studente' %}");
		$.ajax({
			url: "{% url 'sportday:get-student' id=class.id %}",
			data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "student": st},
			dataType: "json",
			method: "POST",
		}).done(function (data) {
			if (data["status"] == "error") {
				displayModalError(
					"{% trans 'Errore durante il recupero dei dati. Il server ha risposto:' %}<br><code>"+data["error"]+"</code><br>La preghiamo di segnalare il problema all'amministratore se dovesse persistere."
				);
			}
			else if (data["status"] == "success") {
				// ui conf
				$("#modal-wait").hide();
				$("#modal-content").show();
				$("#modal-close-btn").show();
				$("#modal-saveclose-btn").show();
				$("#modal-save-btn").show();
				$('input:checkbox').prop('checked', false);
				// load data
				$("#student-id").val(st);
				$("#modal-title").text(data["full_name"]);
				$("#student-last_name").text(data["last_name"]);
				$("#student-first_name").text(data["first_name"]);
				$("#student-date_of_birth").text(data["date_of_birth"]);
				for (i=0; i < data["competitions"].length; i++) {
					$("#c-"+data["competitions"][i]).prop("checked", true);
				}
			}
			else {
				displayModalError("{% trans 'Errore durante il recupero dei dati. Nessuna informazione di debug disponibile.' %}");
			}
		});
	}

	function saveprofile(closemodal=false) {
		$("#modal-error-alert").hide();
		$("#modal-success-alert").hide();
		$("#modal-wait").show();
		var studentid = $("#student-id").val(),
			 competitions = $("input:checkbox:checked"),
			 ajaxcomps = Array();
		for (i=0; i < competitions.length; i++) {
			ajaxcomps.push(competitions[i].id.replace("c-", ""));
		}
		return $.ajax({
			url: "{% url 'sportday:save-student' id=class.id %}",
			data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "student": studentid, "competitions": JSON.stringify(ajaxcomps)},
			dataType: "json",
			method: "POST"
		}).done(function (data) {
			$("#modal-wait").hide();
			$("#table").DataTable().ajax.reload();
			$(window).scrollTop(pos);
			if (data["status"]=="success") {displayModalSuccess("{% trans 'Salvataggio effettuato con successo.' %}"); if (closemodal) $("#studentbox").modal('toggle');}
			else {
				displayModalError(
					"{% trans 'Errore durante il salvataggio dei dati. Il server ha risposto:' %}<br><code>"+data["error"]+"</code><br>La preghiamo di segnalare il problema all'amministratore se dovesse persistere."
				);
				return 1;
			}
		});
	}

	$("#modal-save-btn").click(function () {
		saveprofile();
	});

	$("#modal-saveclose-btn").click(function () {
		saveprofile(true);
	});

</script>
{% endblock %}

sportday/templates/sportday/competitions.html
{% extends "sportday/base.html" %}{% load i18n static %}
{% block title %}{% trans "Gare" %}{% endblock %}
{% block standardcontent %}
<p class="page-title">{% trans "Gare" %}</p>
<br>
<div class="row">
	{% for c in competitions %}
	<div class="col-md-3">
		<a href="{% url 'sportday:competition' id=c.id %}" class="btn btn-lg btn-primary btn-block">{{ c }}</a>
	</div>
	{% endfor %}
</div>
{% endblock %}